[project]
name = "project-11-jackcompiler"
version = "0.1.0"
description = "verifies the functionality of the jack compiler"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradescope-utils>=0.5.0",
]
